require "spec"
require "../src/cocol/logger.cr"
require "../src/cocol/node/ledger/model/block.cr"

describe "Ledger::Model::Block" do
  context "Creating genesis block" do
    genesis = Ledger::Model::Block.genesis

    it "uses correct timestamp" do
      genesis.timestamp.should eq(1449970561_i64)
    end

    it "has 'Olivia' as parent" do
      genesis.previous_hash.should eq("Olivia")
    end

    it "has block height of 0" do
      genesis.height.should eq(0)
    end

    it "has the correct nonce" do
      genesis.nonce.should eq(144)
    end

    it "has the correct hash" do
      genesis.hash.should eq("00f82f15d9fee292860b2a37183d769efd3b617451c04017f700238fd472e8bb")
    end
  end

  context "Generic block" do
    block = Ledger::Model::Block.new(
      height: 0,
      transactions: Array(Ledger::Model::Transaction).new,
      previous_hash: "abcdefhash",
      difficulty: "20000010"
    )

    it "should have autogenerated values" do
      block.hash.should be_truthy
      block.nonce.should be_truthy
      block.timestamp.should be_truthy
    end
  end
end
